-- Migration 009: Schüler-eigener Login
-- Fahrschüler bekommen einen Einladungscode von ihrer Fahrschule
-- und können sich damit registrieren um den Theorie-Trainer zu nutzen.

-- Invite codes generated by driving schools
CREATE TABLE IF NOT EXISTS public.student_invites (
  id           uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id    uuid        NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  code         text        NOT NULL,
  max_uses     integer     NOT NULL DEFAULT 50,
  used_count   integer     NOT NULL DEFAULT 0,
  expires_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT student_invites_code_unique UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS student_invites_code_idx ON public.student_invites (code);

-- Students linked to their driving school
CREATE TABLE IF NOT EXISTS public.students (
  id           uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id      uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tenant_id    uuid        NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  name         text        NOT NULL DEFAULT '',
  invite_id    uuid        REFERENCES public.student_invites(id),
  created_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT students_user_unique UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS students_tenant_idx ON public.students (tenant_id);
CREATE INDEX IF NOT EXISTS students_user_idx ON public.students (user_id);

-- RLS for student_invites: tenant owners can manage, students can read (to validate)
ALTER TABLE public.student_invites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant owners can manage invites"
  ON public.student_invites
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.tenant_users tu
      WHERE tu.tenant_id = student_invites.tenant_id
        AND tu.user_id = auth.uid()
        AND tu.role IN ('owner', 'admin')
    )
  );

CREATE POLICY "Anyone can validate invite codes"
  ON public.student_invites
  FOR SELECT
  USING (true);

-- RLS for students: students see own record, tenant owners see their students
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Students can read own record"
  ON public.students
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Students can insert own record"
  ON public.students
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Tenant owners can see their students"
  ON public.students
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.tenant_users tu
      WHERE tu.tenant_id = students.tenant_id
        AND tu.user_id = auth.uid()
        AND tu.role IN ('owner', 'admin')
    )
  );
